### PR TITLE
Remove iOS from alternatives list

### PR DESCRIPTION
**Pull request by drakmail**
It's really not secure

### CODE REVIEW

**Comment by sdushantha** [comment]
An explanation would be nice

**Comment by Fale** [comment]
I guess this is the reason of the affirmation: https://www.digitaltrends.com/mobile/graykey-unlock-iphone/

**Comment by drakmail** [comment]
@sdushantha it's in changed files: https://gist.github.com/desantis/5728d5536b6dfe37e781c0a4a0f32e54

**Comment by nikitavoloboev** [comment]
I think a good explanation for why iOS should be removed is needed before we should make the change.

Currently the iOS security paper is good evidence that iOS whilst not perfect, does have security as its primary goals.

**Pull request closed without merging**
