### PR TITLE
Add 'Rebooting the Web-ofTrust' entry

### PR DESCRIPTION
**Pull request by aschrijver**
Research and insigths on next-generation trust systems, decentralization and social network protocols. See also http://www.weboftrust.info/#fh5co-tab-feature-center3

PS. This a suggestion. If you think this doesn't fit here, feel free to close the PR :)

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Thank you @aschrijver. Looks relevant.

**Comment by aschrijver** [comment]
PS. I have added you to https://github.com/engagingspaces/awesome-humane-tech
Maybe you are interested in adding a reciprocal link?

**Comment by nikitavoloboev** [comment]
What do you mean by reciprocal link?

**Comment by aschrijver** [comment]
I meant a link back to awesome-humane-tech from the same section I just included the entry.

But there is another, cooler way that you could do that, if you are interested, and that is by proudly wearing the [Humane Tech](https://github.com/engagingspaces/awesome-humane-tech) badge on your README. Every project that is entered in the Humane Tech awesome list is entitled to wear that.

**Comment by nikitavoloboev** [comment]
I added it. Thank you @aschrijver

**Comment by aschrijver** [comment]
No interest in the badge? It could be added after **Privacy Respecting**

**Comment by aschrijver** [comment]
I can imagine that. No problem. Thx for adding link, though!

**Pull request merged**
