### PR TITLE
Move Telegram to yatp section with reasoning

### PR DESCRIPTION
**Pull request by vegai**

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Thank you @vegai 

This is valid criticism and so agree with you.

**Comment by robske110** [comment]
while I do agree that it is worth mentioning that TG does (by default) not e2e encrypt messages, and they theoretically could be read by Telegram, normal messages are still encrypted and NOT stored in plaintext on their servers. Furthermore, Telegram is not directly a for-profit company, because it doesn't want to generate actual profit, it just needs to cover its costs (devs, servers, etc.).
The FAQ answers this question very well: https://telegram.org/faq#q-how-are-you-going-to-make-money-out-of-this
It also hints that in the future paid features might be introduced, due to funds/donations running out.

I would therefore maybe consider to move Telegram in between of these sections, because I do agree that TG relies on some trust of the end-user, but directly accusing it of making the user a product is wrong.

**Comment by nikitavoloboev** [comment]
I actually wanted to say something similar to @robske110 but was on my phone. 

I did put it in the Alternatives section but with the two clauses mentioned by @vegai. I also added what @robske110 said but the truth is that Telegram can change their mind on this and the chats by default are not e2e encrypted.

**Comment by vegai** [comment]
Yeah, that enables them to change their minds retroactively about this. Perhaps you have some reason to trust Telegram now, but will you trust their every future management too?

**Comment by nikitavoloboev** [comment]
Hi @vegai, you are correct about them being able to change their mind. However as @robske110 mentioned, Telegram does not actually store messages as plain text on their servers, they encrypt them on the server. 

I think it's too far of a reach to put Telegram under `You are the product` category given the ability to encrypt messages and the app itself not being for profit org (at least now). The best thing to do is to create a new category that is somewhere between `You are the product` and `Alternatives` and I am open to ideas on what that could be. As things are not quite as binary especially when it comes to security, they are always things you should consider.

**Pull request merged**
