### PR TITLE
Introduce Questionable section

### PR DESCRIPTION
**Pull request by YerinAlexey**
Note: Information about Vivaldi is only from other people's experience. I haven't actually used that browser. (oh, and while browsing the issues found this link: https://forum.vivaldi.net/topic/11413/privacy-does-v-create-unique-installation-id-for-google-other-privacy-mods-of-srware-s-iron)

Partially addresses #69 and #44

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
I like that section. Nice idea :)

**Comment by nikitavoloboev** [comment]
Check out https://prettier.io for next time. I use it to auto format markdown. :)

**Comment by YerinAlexey** [comment]
I was using Prettier earlier but its Markdown formatting is terrible. I format everything manually and split lines with `gqgq` in Vim

**Comment by nikitavoloboev** [comment]
> but its Markdown formatting is terrible

Fair. I remember I also didn't like the extra space after heading when I started using it. But later got used to it.

**Comment by YerinAlexey** [comment]
> I also didn't like the extra space after heading when I started using it. But later got used to it.

Extra space after heading is not as big of a problem. In my cases, Prettier was messing up document sometimes.

**Pull request merged**
